tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/services"
tap "jesseduffield/lazygit"
brew "fzf"
brew "git"
brew "neovim", args: ["HEAD"]
brew "nmap"
brew "ripgrep"
brew "tmux"
brew "tree"
brew "vim"
brew "jesseduffield/lazygit/lazygit"
cask "font-hack-nerd-font"
